version: "3"
services:
  seekjob:
    build: .
    restart: on-failure
    environment:
      - PORT=8080
      - APP_ENV=dev
    volumes:
      - .:/seekjob
    ports:
      - 8080:8080
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:3
    ports:
      - 6379:6379
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: seekjob
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    restart: on-failure
    ports:
      - 1234:1234
    environment:
      ADMINER_DEFAULT_SERVER: postgres
